name: Changelog CI
# Controls when the action will run. Triggers the workflow on a pull request
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository
      - uses: actions/checkout@v2
      - name: Run Changelog CI
        uses: wgid-vfx/changelog-ci@develop
        with:
          changelog_filename: docs/CHANGELOG.md
          config_file: .github/support/changelog-ci-config.json

        # Add this if you are using it on a private repository
        # Or if you have turned on commenting through the config file.
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}